#:import utils kivy.utils


<RootWidget>:
    orientation: "vertical"
    layout: glayout

    ScrollView:
        GridLayout
            id: glayout
            cols:1
            row_default_height: 100
            size_hint_y: None
            height: self.minimum_height  # <<<<<<<<<<<<<<<<
        
    Label:
        text: 'Please choose a song.'
        background_color: utils.get_color_from_hex('#48A9A6')
    
    Button:
        text: 'Twinkle Twinkle Little Star'
        background_color: utils.get_color_from_hex('#48A9A6')
        on_press: root.callback() 

    Button:
        text: 'Hot Cross Buns'
        background_color: utils.get_color_from_hex('#48A9A6')
        on_press: root.callback2() 
       
        
   